name: Check latest Cloudflared version

on:
  schedule:
    - cron: '15 */6 * * *'
  workflow_dispatch:

concurrency:
  group: check
  cancel-in-progress: true

jobs:
  version-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Get the latest version of Cloudflared
        run: |
          curl -s https://api.github.com/repos/cloudflare/cloudflared/releases | jq -r '[.[] | select(.prerelease == false)][0] | .tag_name' > version
          echo "CLOUDFLARED_VERSION=$(cat version)" >> $GITHUB_ENV

      - name: Commit & Push changes
        id: commit
        uses: iarekylew00t/verified-bot-commit@v2
        with:
          message: 'Version updated to: ${{ env.CLOUDFLARED_VERSION }}'
          token: ${{ secrets.GH_PAT }}
          update-local: true
          auto-stage: true
          files: |
            **
